from manim import *


TEXT = {
    "en": {
        "title": "Dependence reveals redundancy",
        "subtitle": "A new vector matters only if it adds a new direction.",
        "visual": {
            "span_plane": "Span{u₁, u₂}",
            "outside": "u₃ outside the span",
            "inside": "u₃ lands in the span",
            "relation": "nontrivial relation",
            "matrix": "homogeneous test",
            "free": "free column",
            "pivot": "pivot",
            "checker": "try cases below",
            "outside_body": "no relation is visible yet",
            "inside_body": "u₃ = u₁ + u₂",
            "relation_body": "u₁ + u₂ − u₃ = 0",
            "matrix_body": "Aα = 0 has a nonzero solution",
            "free_body": "α₃ = −1 gives α=(1,1,−1)",
            "independent": "independent: only the zero relation",
            "dependent": "dependent: some nonzero relation",
            "zero_relation": "zero relation",
            "nonzero_relation": "nonzero relation",
            "row_rule": "pivot in every column <-> independent",
        },
        "states": [
            (
                "Start with two directions",
                "The first two vectors generate a plane of outputs.",
                "Span{u₁, u₂}",
            ),
            (
                "A third vector may add information",
                "If u₃ is outside that plane, it is not generated by the previous vectors.",
                "u₃ not in Span{u₁, u₂}",
            ),
            (
                "Dependence begins inside the span",
                "Once u₃ equals u₁+u₂, the third vector repeats information already present.",
                "u₃ = u₁ + u₂",
            ),
            (
                "Move everything to one side",
                "Redundancy becomes a nontrivial relation because the coefficients are not all zero.",
                "u₁ + u₂ − u₃ = 0",
            ),
            (
                "Row reduction finds the same relation",
                "A non-pivot column gives a free coefficient in Aα = 0.",
                "α₃ free -> nonzero α",
            ),
            (
                "Independence means no redundancy",
                "Only the all-zero relation means every listed vector really matters.",
                "use the checker below",
            ),
        ],
        "conclusion": "Dependence is not failure to span. It is redundancy: at least one listed vector can be rebuilt from the others.",
    },
    "zh-hk": {
        "title": "相依揭示冗餘",
        "subtitle": "新向量只有加入新方向時才真正必要。",
        "visual": {
            "span_plane": "Span{u₁, u₂}",
            "outside": "u₃ 在張成外",
            "inside": "u₃ 落入張成",
            "relation": "非平凡關係",
            "matrix": "齊次系統測試",
            "free": "自由欄",
            "pivot": "pivot",
            "checker": "下方再試例子",
            "outside_body": "暫時看不見關係式",
            "inside_body": "u₃ = u₁ + u₂",
            "relation_body": "u₁ + u₂ − u₃ = 0",
            "matrix_body": "Aα = 0 有非零解",
            "free_body": "α₃ = −1 給出 α=(1,1,−1)",
            "independent": "線性獨立：只有零關係",
            "dependent": "線性相依：有非零關係",
            "zero_relation": "零關係",
            "nonzero_relation": "非零關係",
            "row_rule": "每欄有 pivot <-> 線性獨立",
        },
        "states": [
            (
                "由兩個方向開始",
                "頭兩個向量生成一個輸出平面。",
                "Span{u₁, u₂}",
            ),
            (
                "第三個向量可能加入資訊",
                "如果 u₃ 在該平面外，它不是由之前向量生成。",
                "u₃ 不屬於 Span{u₁, u₂}",
            ),
            (
                "落入張成時開始相依",
                "一旦 u₃ 等於 u₁+u₂，第三個向量只重覆已有資訊。",
                "u₃ = u₁ + u₂",
            ),
            (
                "把所有項移到同一邊",
                "冗餘變成非平凡關係，因為係數不全為零。",
                "u₁ + u₂ − u₃ = 0",
            ),
            (
                "行化簡找到同一關係",
                "非 pivot 欄會在 Aα = 0 中產生自由係數。",
                "α₃ 自由 -> 非零 α",
            ),
            (
                "線性獨立表示沒有冗餘",
                "只有全零關係，才表示每個列出的向量都真正有作用。",
                "下方檢查例子",
            ),
        ],
        "conclusion": "相依不等於不能張成。相依表示冗餘：至少一個列出的向量可由其他向量重建。",
    },
    "zh-cn": {
        "title": "依赖揭示冗余",
        "subtitle": "新向量只有加入新方向时才真正必要。",
        "visual": {
            "span_plane": "Span{u₁, u₂}",
            "outside": "u₃ 在张成外",
            "inside": "u₃ 落入张成",
            "relation": "非平凡关系",
            "matrix": "齐次系统测试",
            "free": "自由列",
            "pivot": "pivot",
            "checker": "下方再试例子",
            "outside_body": "暂时看不见关系式",
            "inside_body": "u₃ = u₁ + u₂",
            "relation_body": "u₁ + u₂ − u₃ = 0",
            "matrix_body": "Aα = 0 有非零解",
            "free_body": "α₃ = −1 给出 α=(1,1,−1)",
            "independent": "线性独立：只有零关系",
            "dependent": "线性依赖：有非零关系",
            "zero_relation": "零关系",
            "nonzero_relation": "非零关系",
            "row_rule": "每列有 pivot <-> 线性独立",
        },
        "states": [
            (
                "由两个方向开始",
                "头两个向量生成一个输出平面。",
                "Span{u₁, u₂}",
            ),
            (
                "第三个向量可能加入信息",
                "如果 u₃ 在该平面外，它不是由之前向量生成。",
                "u₃ 不属于 Span{u₁, u₂}",
            ),
            (
                "落入张成时开始依赖",
                "一旦 u₃ 等于 u₁+u₂，第三个向量只重复已有信息。",
                "u₃ = u₁ + u₂",
            ),
            (
                "把所有项移到同一边",
                "冗余变成非平凡关系，因为系数不全为零。",
                "u₁ + u₂ − u₃ = 0",
            ),
            (
                "行化简找到同一关系",
                "非 pivot 列会在 Aα = 0 中产生自由系数。",
                "α₃ 自由 -> 非零 α",
            ),
            (
                "线性独立表示没有冗余",
                "只有全零关系，才表示每个列出的向量都真正有作用。",
                "下方检查例子",
            ),
        ],
        "conclusion": "依赖不等于不能张成。依赖表示冗余：至少一个列出的向量可由其他向量重建。",
    },
}


class LinearDependenceRedundancyStoryBase(Scene):
    """MATH1030 6.4: dependence as redundancy."""

    locale = "en"
    font = "Avenir Next"

    def label(self, value, font_size=28, color=WHITE, weight=NORMAL, max_width=6.8):
        text = Text(value, font=self.font, font_size=font_size, color=color, weight=weight)
        if text.width > max_width:
            text.scale_to_fit_width(max_width)
        return text

    def formula_card(self, title, body, color=GREEN_B, width=5.9, height=0.9):
        box = RoundedRectangle(
            corner_radius=0.08,
            width=width,
            height=height,
            stroke_color=color,
            fill_color=BLACK,
            fill_opacity=0.22,
        )
        title_mob = self.label(title, font_size=18, color=color, weight=MEDIUM, max_width=width * 0.9)
        body_mob = self.label(body, font_size=22, max_width=width * 0.9)
        content = VGroup(title_mob, body_mob).arrange(DOWN, buff=0.08).move_to(box)
        return VGroup(box, content)

    def fit_visual(self, visual, max_width=7.25, max_height=3.35):
        if visual.width > max_width:
            visual.scale_to_fit_width(max_width)
        if visual.height > max_height:
            visual.scale_to_fit_height(max_height)
        return visual

    def plane_point(self, a, b):
        origin = LEFT * 2.0 + DOWN * 1.0
        u_vec = RIGHT * 1.32 + UP * 0.24
        v_vec = RIGHT * 0.46 + UP * 0.98
        return origin + a * u_vec + b * v_vec

    def plane_surface(self):
        surface = Polygon(
            self.plane_point(-1.35, -1.05),
            self.plane_point(1.45, -1.05),
            self.plane_point(1.45, 1.05),
            self.plane_point(-1.35, 1.05),
            stroke_color=GREEN_B,
            stroke_width=1.4,
            fill_color=GREEN_E,
            fill_opacity=0.18,
        )
        grid = VGroup()
        for a in [-1.0, -0.5, 0, 0.5, 1.0]:
            grid.add(Line(self.plane_point(a, -1.0), self.plane_point(a, 1.0), stroke_width=0.7, color=GREEN_C).set_opacity(0.45))
        for b in [-0.75, -0.25, 0.25, 0.75]:
            grid.add(Line(self.plane_point(-1.25, b), self.plane_point(1.35, b), stroke_width=0.7, color=GREEN_C).set_opacity(0.45))
        label = self.label(TEXT[self.locale]["visual"]["span_plane"], font_size=20, color=GREEN_B, weight=MEDIUM, max_width=2.6)
        label.next_to(surface, UP, buff=0.1)
        return VGroup(surface, grid, label)

    def vector_arrow(self, end, label, color, label_direction=UP):
        arrow = Arrow(
            self.plane_point(0, 0),
            end,
            buff=0,
            color=color,
            max_tip_length_to_length_ratio=0.18,
            stroke_width=4,
        )
        tag = self.label(label, font_size=20, color=color, weight=MEDIUM, max_width=0.9)
        tag.next_to(arrow.get_end(), label_direction, buff=0.08)
        return VGroup(arrow, tag)

    def two_direction_visual(self):
        labels = TEXT[self.locale]["visual"]
        plane = self.plane_surface()
        u1 = self.vector_arrow(self.plane_point(1.0, 0), "u₁", BLUE_B, DOWN)
        u2 = self.vector_arrow(self.plane_point(0, 1.0), "u₂", GREEN_B, LEFT)
        sample = VGroup(*[
            Dot(self.plane_point(a, b), radius=0.035, color=YELLOW_B)
            for a in [-1, 0, 1]
            for b in [-0.75, 0, 0.75]
        ])
        card = self.formula_card(labels["span_plane"], "u₁, u₂", GREEN_B, width=4.8)
        return self.fit_visual(VGroup(VGroup(plane, sample, u1, u2), card).arrange(DOWN, buff=0.22))

    def outside_visual(self):
        labels = TEXT[self.locale]["visual"]
        plane = self.plane_surface()
        u1 = self.vector_arrow(self.plane_point(0.9, 0), "u₁", BLUE_B, DOWN)
        u2 = self.vector_arrow(self.plane_point(0, 0.9), "u₂", GREEN_B, LEFT)
        outside_end = self.plane_point(0.82, 0.82) + UP * 1.1 + RIGHT * 0.4
        u3 = self.vector_arrow(outside_end, "u₃", RED_B, RIGHT)
        drop = DashedLine(self.plane_point(0.82, 0.82), outside_end, dash_length=0.06, stroke_width=2, color=RED_B)
        cross = VGroup(
            Line(outside_end + LEFT * 0.11 + UP * 0.11, outside_end + RIGHT * 0.11 + DOWN * 0.11, stroke_width=3, color=RED_B),
            Line(outside_end + LEFT * 0.11 + DOWN * 0.11, outside_end + RIGHT * 0.11 + UP * 0.11, stroke_width=3, color=RED_B),
        )
        card = self.formula_card(labels["outside"], labels["outside_body"], RED_B, width=5.8)
        return self.fit_visual(VGroup(VGroup(plane, u1, u2, drop, u3, cross), card).arrange(DOWN, buff=0.22))

    def inside_visual(self):
        labels = TEXT[self.locale]["visual"]
        plane = self.plane_surface()
        u1_end = self.plane_point(1.0, 0)
        u2_step_end = self.plane_point(1.0, 1.0)
        u1 = self.vector_arrow(u1_end, "u₁", BLUE_B, DOWN)
        u2 = self.vector_arrow(self.plane_point(0, 1.0), "u₂", GREEN_B, LEFT)
        u3 = self.vector_arrow(u2_step_end, "u₃", PURPLE_B, RIGHT)
        path = VGroup(
            Line(self.plane_point(0, 0), u1_end, stroke_width=3, color=BLUE_B),
            Line(u1_end, u2_step_end, stroke_width=3, color=GREEN_B),
            Dot(u2_step_end, radius=0.055, color=PURPLE_B),
        )
        card = self.formula_card(labels["inside"], labels["inside_body"], PURPLE_B, width=4.8)
        return self.fit_visual(VGroup(VGroup(plane, path, u1, u2, u3), card).arrange(DOWN, buff=0.22))

    def relation_visual(self):
        labels = TEXT[self.locale]["visual"]
        cards = VGroup(
            self.formula_card("+1", "u₁", BLUE_B, width=1.45, height=0.95),
            self.formula_card("+1", "u₂", GREEN_B, width=1.45, height=0.95),
            self.formula_card("-1", "u₃", PURPLE_B, width=1.45, height=0.95),
        ).arrange(RIGHT, buff=0.16)
        equals = self.label("=", font_size=42, color=GRAY_B)
        zero = Circle(radius=0.36, stroke_color=YELLOW_B, fill_color=YELLOW_E, fill_opacity=0.2)
        zero_label = self.label("0", font_size=30, color=YELLOW_B, weight=BOLD).move_to(zero)
        equation = VGroup(cards, equals, VGroup(zero, zero_label)).arrange(RIGHT, buff=0.22)
        card = self.formula_card(labels["relation"], labels["relation_body"], YELLOW_B, width=6.1)
        return self.fit_visual(VGroup(equation, card).arrange(DOWN, buff=0.42))

    def matrix_visual(self):
        labels = TEXT[self.locale]["visual"]
        matrix_lines = VGroup(
            self.label("RREF(A) = [ 1  0  1 ]", font_size=24, color=WHITE, max_width=5.8),
            self.label("          [ 0  1  1 ]", font_size=24, color=WHITE, max_width=5.8),
            self.label("          [ 0  0  0 ]", font_size=24, color=WHITE, max_width=5.8),
        ).arrange(DOWN, buff=0.08, aligned_edge=LEFT)
        col_tags = VGroup(
            self.formula_card(labels["pivot"], "u₁", BLUE_B, width=1.6, height=0.75),
            self.formula_card(labels["pivot"], "u₂", GREEN_B, width=1.6, height=0.75),
            self.formula_card(labels["free"], "u₃", RED_B, width=1.6, height=0.75),
        ).arrange(RIGHT, buff=0.2)
        card = self.formula_card(labels["matrix"], labels["free_body"], RED_B, width=6.15)
        return self.fit_visual(VGroup(matrix_lines, col_tags, card).arrange(DOWN, buff=0.3))

    def recap_visual(self):
        labels = TEXT[self.locale]["visual"]
        cards = VGroup(
            self.formula_card(labels["zero_relation"], labels["independent"], BLUE_B, width=2.55, height=1.05),
            self.formula_card(labels["nonzero_relation"], labels["dependent"], RED_B, width=2.55, height=1.05),
            self.formula_card(labels["checker"], labels["row_rule"], PURPLE_B, width=2.65, height=1.05),
        ).arrange(RIGHT, buff=0.18)
        summary = self.formula_card(labels["matrix"], labels["matrix_body"], YELLOW_B, width=6.8)
        return self.fit_visual(VGroup(cards, summary).arrange(DOWN, buff=0.34))

    def state_visual(self, index):
        if index == 0:
            return self.two_direction_visual()
        if index == 1:
            return self.outside_visual()
        if index == 2:
            return self.inside_visual()
        if index == 3:
            return self.relation_visual()
        if index == 4:
            return self.matrix_visual()
        return self.recap_visual()

    def construct(self):
        copy = TEXT[self.locale]
        title = self.label(copy["title"], font_size=36, weight=BOLD, max_width=7.25)
        subtitle = self.label(copy["subtitle"], font_size=22, color=GRAY_B, max_width=7.35)
        header = VGroup(title, subtitle).arrange(DOWN, buff=0.16).to_edge(UP)

        self.play(FadeIn(header, shift=DOWN * 0.2))

        current = None
        for index, (caption, focus, operation) in enumerate(copy["states"]):
            caption_mob = self.label(caption, font_size=27, weight=MEDIUM, max_width=7.0)
            visual = self.state_visual(index)
            focus_mob = self.label(focus, font_size=20, color=GRAY_B, max_width=7.25)
            operation_mob = self.label(operation, font_size=23, color=BLUE_B, max_width=7.25)
            group = VGroup(caption_mob, visual, focus_mob, operation_mob).arrange(DOWN, buff=0.2)
            group.next_to(header, DOWN, buff=0.28)

            if current is None:
                self.play(FadeIn(group, shift=UP * 0.15))
            else:
                self.play(FadeOut(current, shift=UP * 0.1), FadeIn(group, shift=UP * 0.1))

            current = group
            self.wait(1.02 if index < len(copy["states"]) - 1 else 1.45)

        conclusion = self.label(copy["conclusion"], font_size=24, color=GREEN_B, max_width=7.4).to_edge(DOWN)
        self.play(FadeIn(conclusion, shift=UP * 0.2))
        self.wait(1.2)


class LinearDependenceRedundancyStoryEn(LinearDependenceRedundancyStoryBase):
    locale = "en"


class LinearDependenceRedundancyStoryZhHk(LinearDependenceRedundancyStoryBase):
    locale = "zh-hk"
    font = "PingFang HK"


class LinearDependenceRedundancyStoryZhCn(LinearDependenceRedundancyStoryBase):
    locale = "zh-cn"
    font = "PingFang SC"


class LinearDependenceRedundancyStory(LinearDependenceRedundancyStoryEn):
    """Backwards-compatible alias for one-off English render commands."""
